### ISSUE TITLE
Unable to import CookieManager 

### ISSUE THREAD

**Issue by InfiniteVortex** [Unattched/EducationSite#1]

**Comment by InfiniteVortex** [comment]
Will work on this tomorrow

**Comment by Unattched** [comment]
Yes have you figured why it can’t resolve the import statement Udhay Kurrimboccus From: InfiniteVortexSent: Monday, June 8, 2020 4:13 PMTo: Unattched/EducationSiteCc: SubscribedSubject: Re: [Unattched/EducationSite] Unable to import CookieManager (#1) Will work on this tomorrow—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by InfiniteVortex** [comment]
This issue has been resolved
